version: '3.0'
services:

  nginx:
    image: nginx:1.19-alpine
    volumes:
    - .:/app
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 2080:80
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
    - .:/app
    - ./docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /app

  db:
    image: postgres:12.3-alpine
    volumes:
    - db-data:/var/lib/postgresql/data/pgdata
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: Symf0nY
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  db-data: